sonar.projectKey=Luminote
sonar.projectName=Luminote
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# Frontend + Backend
sonar.sources=frontend,backend

# Exclude unnecessary folders
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**

# SonarQube server
sonar.host.url=http://localhost:9000
sonar.login=sqp_318b52da9004f72c39ab96400403765eb0bc4e62